# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build
      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 7.23.0
          run_install: true
      - name: Build
        run: pnpm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      # Run a build step here if your project requires

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 59ba3cf1d1cb7b3df87aef2d5db06c22
          projectName: jlmr-qwik
          directory: dist
